sudo: false
language: java
script: mvn verify
after_success: mvn deploy -Dmaven.test.skip=true --settings settings.xml
jdk:
- oraclejdk7
env:
  global:
    secure: cGlQH0HD1ABUSltPLT3sk7q4/QoB4OiRx7AeKkSlFgXXNMUapXQIQ+wiZSLWzbtuTmK/beAnOxaaORFI1b3vX7b/AjezUoDt0EZpyTbrfWkMLDo2lFzfLLr5BMgzk6A1zEPFSKgu9tWlat1G8a1i8WHR5Pw3gRTVCAdiLMGkSPqHfem5ddDngi4Ar9/2+4m2OyuF/lASBMlN2+9b7LTSaf76B0lYb6p0IcILjYu0RcMBHeGhFzA8oV1XFRTu2+AGe7MEO/DbsSsUuWtPkU1SGm/GTqYHrGMZEg2OE5hfrIaQNqOMG/TdLyo4BHc4KUdJUJGQROjVvDzCvuYyaxIo+QKtJnCNTly/r5pVFLCAdHXZr3767jlxcI9uVezgrlXyDxyBqQL40tIkTCNUayGDeGv46eC6KsmsL0gNr9RZhzuRiE/HJihNbz8WZb6qAS9JcqpAh/7gxfC+w6rD4opJgHat5C2OhR0oFei0QHelxSkub/GkyFrJZmclyJAh6OUbEC2ZTZyoxjI0HhODW55A/09qGTJrb7lxCpocs+Yx/ibKzqmMG+BEJ6HqCuQn0p5ZY4ByvOXpB09Ocsu6hvPsMcgkN6iVQ2KedWpAn5d/TTYs6xRFsDy8215JXUU1hMd9BPtxRWM//oLS0hdkqEhBDf41s6Unvu4pxAknvDZv4KA=
